<p><b>[INFO]</b>&nbsp;GET Request : url=https://dev.api.zinnia.io/case/v1/cases/12398305 <br> path_url=/case/v1/cases/12398305 <br> headers={'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive'} <br> body=None <br> </p><p><b>[INFO]</b>&nbsp;GET Response : url=https://dev.api.zinnia.io/case/v1/cases/12398305 <br> status=401, reason=Unauthorized <br> headers={'Date': 'Sat, 13 Sep 2025 12:22:04 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Connection': 'keep-alive', 'WWW-Authenticate': 'Bearer realm="login.dev.zinnia.com", error="invalid_token"', 'Content-Length': '26', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'Host', 'X-Kong-Response-Latency': '1', 'Server': 'kong/3.10.0.5-enterprise-edition', 'X-Kong-Request-Id': '48674a0b3a7f0f727b56ae73083c7703'} <br> body={"message":"Unauthorized"} <br> </p><p><b>[INFO]</b>&nbsp;C:\Users\sharmash\AppData\Roaming\Python\Python312\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dev.api.zinnia.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings<br>  warnings.warn(</p><p style="color: red"><b>[FAIL]</b>&nbsp;HTTPError: 401 Client Error: Unauthorized for url: https://dev.api.zinnia.io/case/v1/cases/12398305</p>